# Generated by Django 2.0.7 on 2018-07-09 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Cargo',
            },
        ),
        migrations.CreateModel(
            name='personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellidos', models.CharField(max_length=100)),
                ('Ci', models.IntegerField()),
                ('Tipo_personal', models.CharField(max_length=30)),
                ('Nro_item', models.IntegerField()),
                ('Responsable', models.BooleanField(default=False)),
                ('Cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responsablesInformacion.cargo')),
            ],
            options={
                'verbose_name_plural': 'Personal',
            },
        ),
        migrations.CreateModel(
            name='unidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_unidad', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Unidad',
            },
        ),
        migrations.AddField(
            model_name='personal',
            name='Unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responsablesInformacion.unidad'),
        ),
    ]
