# Generated by Django 2.0.7 on 2018-07-31 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DeterminacionForm', '0010_auto_20180731_2048'),
        ('responsablesInformacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='Cargo',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='Unidad',
        ),
        migrations.DeleteModel(
            name='cargo',
        ),
        migrations.DeleteModel(
            name='personal',
        ),
        migrations.DeleteModel(
            name='unidad',
        ),
    ]
