# Generated by Django 2.0.7 on 2018-07-25 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('responsablesInformacion', '0001_initial'),
        ('DeterminacionForm', '0004_auto_20180725_0517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datosformulario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=10)),
                ('codigo', models.IntegerField()),
                ('nombre_entidad', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Datosformulario',
            },
        ),
        migrations.CreateModel(
            name='formularios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gestion', models.IntegerField()),
                ('Fecha', models.DateField()),
                ('Cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responsablesInformacion.cargo')),
                ('ResponsableInformacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responsablesInformacion.personal')),
            ],
            options={
                'verbose_name_plural': 'Lista de Formularios',
            },
        ),
        migrations.CreateModel(
            name='objetivos_gestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.CharField(max_length=500)),
                ('Resultados', models.CharField(max_length=500)),
                ('Beneficiarios', models.CharField(choices=[('Estudiantes Afiliados', 'Estudiantes Afiliados'), ('Estudiantes en General', 'Estudiantes en General')], default='Beneficiarios', max_length=30)),
                ('Formularios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DeterminacionForm.formularios')),
            ],
            options={
                'verbose_name_plural': 'Objetivos de Gestion',
            },
        ),
    ]
