# Generated by Django 2.0.7 on 2018-07-31 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DeterminacionForm', '0010_auto_20180731_2048'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Datosformulario',
        ),
        migrations.RemoveField(
            model_name='objetivos_gestion',
            name='Formularios',
        ),
        migrations.DeleteModel(
            name='formularios',
        ),
        migrations.DeleteModel(
            name='objetivos_gestion',
        ),
    ]
