# Generated by Django 2.0.7 on 2018-07-17 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='objetivo',
        ),
    ]
