# Generated by Django 2.0.7 on 2018-07-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prueba', '0002_delete_objetivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='objetivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gestion', models.IntegerField()),
                ('fecha', models.DateField()),
                ('Descripcion', models.CharField(max_length=500)),
                ('Resultados', models.CharField(max_length=200)),
                ('Beneficiarios', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Objetivo Prueba',
            },
        ),
    ]
