# Generated by Django 2.0.7 on 2018-07-19 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0003_objetivo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='objetivo',
        ),
    ]
